const ARCHIVE_KEY='workneo-listas-arquivadas-v1';
const COSTURA_KEY='workneo-costura-lotes-v2';
const LEGACY_KEY='workneo-costureiras-relatorio-v1';
const LEGACY_MIGRATED_KEY='workneo-costura-legacy-migrated-v1';
const EXCLUDED=new Set(['MÁSCARA PROTETORA','MOUSE PAD','MOUSE PAD GAMER','PORTA COPOS']);
const readArr=k=>{try{const x=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(x)?x:[]}catch{return[]}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const total=l=>Object.values(l?.items||{}).reduce((s,x)=>s+(Number(x?.total)||0),0);
const activeLists=()=>readArr('almox-lists');
const archivedLists=()=>readArr(ARCHIVE_KEY);
const lots=()=>readArr(COSTURA_KEY);
function migrateLegacy(){const legacy=readArr(LEGACY_KEY);if(!legacy.length)return;const current=lots();const known=new Set(current.map(x=>String(x?.legacyId||'' )).filter(Boolean));const migrated=legacy.filter(x=>x&&x.id&&!known.has(String(x.id))).map(x=>({id:`legacy-${x.id}`,legacyId:String(x.id),date:String(x.createdAt||'').slice(0,10)||new Date().toISOString().slice(0,10),costureira:String(x.costureira||x.seamstress||'COSTURA INTERNA'),pedido:String(x.orderNumber??x.numeroPedido??x.pedido??''),listId:String(x.listId||''),listName:String(x.listName||''),createdAt:x.createdAt||new Date().toISOString(),items:[{product:x.product,color:x.color||'SEM COR',qty:Number(x.qty||0)}]})).filter(x=>x.listId&&x.items[0].product&&x.items[0].qty>0);if(migrated.length)save(COSTURA_KEY,[...current,...migrated]);try{localStorage.setItem(LEGACY_MIGRATED_KEY,new Date().toISOString())}catch{}}
migrateLegacy();
const sentMap=id=>{const m=new Map();lots().filter(l=>String(l?.listId)===String(id)).forEach(l=>(l.items||[]).forEach(x=>{const k=`${x.product}__${x.color||'SEM COR'}`;m.set(k,(m.get(k)||0)+Number(x.qty||0))}));return m};
function readyToArchive(list){if(!list?.id)return false;const items=Object.values(list.items||{}).filter(x=>x?.product&&!EXCLUDED.has(String(x.product).trim().toUpperCase())&&Number(x.total||0)>0);if(!items.length)return false;const sent=sentMap(list.id);return items.every(x=>Number(sent.get(`${x.product}__${x.color||'SEM COR'}`)||0)>=Number(x.total||0));}
function archiveList(list){if(!list?.id)return;const lists=activeLists(),target=lists.find(x=>String(x?.id)===String(list.id));if(!target)return;if(!confirm(`Arquivar a lista "${list.name||'Lista'}"?\n\nA lista sairá da aba LISTAS e ficará disponível em ARQUIVADAS. Os registros de costura continuam preservados.`))return;save(ARCHIVE_KEY,[...archivedLists().filter(x=>String(x?.id)!==String(target.id)),{...target,archivedAt:new Date().toISOString()}]);save('almox-lists',lists.filter(x=>String(x?.id)!==String(target.id)));if(String(localStorage.getItem('almox-current')||'')===String(target.id))localStorage.removeItem('almox-current');location.reload()}
function openArchived(){let old=document.getElementById('workneo-archive-overlay');if(old)old.remove();const o=document.createElement('div');o.id='workneo-archive-overlay';o.innerHTML='<div class="wa-panel"><div class="wa-head"><div><small>WORKNEO · ALMOXARIFADO</small><h2>🗂️ Listas arquivadas</h2></div><button id="wa-close">×</button></div><div class="wa-body" id="wa-body"></div></div>';document.body.appendChild(o);o.onclick=e=>{if(e.target===o)o.remove()};o.querySelector('#wa-close').onclick=()=>o.remove();renderArchived(o.querySelector('#wa-body'))}
function renderArchived(body){const lists=archivedLists().sort((a,b)=>String(b.archivedAt||'').localeCompare(String(a.archivedAt||'')));if(!lists.length){body.innerHTML='<div class="wa-empty">Nenhuma lista arquivada.</div>';return}body.innerHTML=lists.map((l,i)=>'<div class="wa-card"><div><b>'+esc(l.name||'Lista')+'</b><small>'+Object.keys(l.items||{}).length+' combinações · '+total(l)+' unidades · arquivada em '+new Date(l.archivedAt).toLocaleDateString('pt-BR')+'</small></div><div class="wa-actions"><button data-restore="'+i+'">↩️ RESTAURAR</button><button class="danger" data-delete="'+i+'">🗑️ EXCLUIR</button></div></div>').join('');body.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{const l=lists[Number(b.dataset.restore)];if(!l||!confirm(`Restaurar a lista "${l.name||'Lista'}"?`))return;const clean={...l};delete clean.archivedAt;save('almox-lists',[...activeLists(),clean]);save(ARCHIVE_KEY,lists.filter(x=>String(x.id)!==String(l.id)));save('almox-current',String(l.id));location.reload()});body.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const l=lists[Number(b.dataset.delete)];if(!l||!confirm(`Excluir permanentemente a lista arquivada "${l.name||'Lista'}"?`))return;save(ARCHIVE_KEY,lists.filter(x=>String(x.id)!==String(l.id)));renderArchived(body)})}
function styleArchive(){if(document.getElementById('workneo-archive-style'))return;const s=document.createElement('style');s.id='workneo-archive-style';s.textContent='.wa-panel{max-width:900px;margin:40px auto;background:#fff;color:#172033;border-radius:20px;overflow:hidden;box-shadow:0 20px 60px #0008}.wa-head{display:flex;justify-content:space-between;align-items:center;padding:18px 20px;border-bottom:1px solid #e5e7eb}.wa-head h2{margin:4px 0}.wa-head button{border:0;border-radius:10px;background:#eef2f7;font-size:24px;width:40px;height:40px;cursor:pointer}.wa-body{padding:16px}.wa-card{display:flex;justify-content:space-between;gap:12px;align-items:center;border:1px solid #e1e5eb;border-radius:14px;padding:14px;margin-bottom:10px}.wa-card small{display:block;color:#667085;margin-top:5px}.wa-actions{display:flex;gap:7px;flex-wrap:wrap}.wa-actions button{border:0;border-radius:9px;padding:9px 11px;font-weight:800;cursor:pointer;background:#1769e0;color:#fff}.wa-actions .danger{background:#fee4e2;color:#b42318}.wa-empty{text-align:center;padding:35px;color:#667085}.wa-archive-current{background:#1769e0!important;color:#fff!important}.wa-card-archive{position:absolute;right:18px;top:50%;transform:translateY(-50%);display:grid;place-items:center;width:48px;height:42px;border-radius:10px;background:#1769e0;color:#fff;font-size:22px;cursor:pointer;z-index:5;user-select:none}.wa-card-archive:focus{outline:3px solid #93c5fd}#workneo-archive-overlay{position:fixed;inset:0;z-index:15000;background:#0008;overflow:auto;padding:16px;box-sizing:border-box}@media(max-width:700px){.wa-panel{margin:10px auto}.wa-card{display:block}.wa-actions{margin-top:10px}.wa-card-archive{right:12px;width:44px;height:40px}}';document.head.appendChild(s)}
function injectArchiveUI(){styleArchive();const quick=document.querySelector('.quick');const currentId=String(localStorage.getItem('almox-current')||'');const current=activeLists().find(x=>String(x?.id)===currentId);if(quick&&!quick.querySelector('.wa-archive-current')&&current){const b=document.createElement('button');b.className='wa-archive-current';b.textContent='🗂️ ARQUIVAR LISTA';b.title='Arquivar esta lista';b.onclick=()=>archiveList(current);quick.appendChild(b)}const nav=document.querySelector('.tabs');if(nav&&!nav.querySelector('.wa-open-archived')){const b=document.createElement('button');b.className='wa-open-archived';b.textContent='🗂️ Arquivadas';b.onclick=openArchived;nav.appendChild(b)}const cards=[...document.querySelectorAll('.list-card')];const lists=activeLists();cards.forEach((card,index)=>{const list=lists[index];if(!list?.id)return;card.querySelectorAll('button[title*="Apagar"],button[title*="Excluir"],button').forEach(old=>{if(old!==card&&(old.textContent||'').includes('🗑️'))old.remove()});if(card.querySelector('.wa-card-archive'))return;const b=document.createElement('span');b.className='wa-card-archive';b.textContent='🗂️';b.title='Arquivar lista';b.setAttribute('role','button');b.setAttribute('tabindex','0');b.onclick=e=>{e.preventDefault();e.stopPropagation();archiveList(list)};b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();archiveList(list)}};card.appendChild(b)})}
function startArchiveUI(){injectArchiveUI();let n=0;const timer=setInterval(()=>{injectArchiveUI();if(++n>=30)clearInterval(timer)},500);const root=document.getElementById('root')||document.body;new MutationObserver(()=>injectArchiveUI()).observe(root,{childList:true,subtree:true})}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',startArchiveUI);else startArchiveUI();