const ARCHIVE_KEY='workneo-listas-arquivadas-v1';
const COSTURA_KEY='workneo-costura-lotes-v2';
const EXCLUDED=new Set(['MÁSCARA PROTETORA','MOUSE PAD','MOUSE PAD GAMER','PORTA COPOS']);
const readArr=k=>{try{const x=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(x)?x:[]}catch{return[]}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const total=l=>Object.values(l?.items||{}).reduce((s,x)=>s+(Number(x?.total)||0),0);
const activeLists=()=>readArr('almox-lists');
const archivedLists=()=>readArr(ARCHIVE_KEY);
const lots=()=>readArr(COSTURA_KEY);
const sentMap=id=>{const m=new Map();lots().filter(l=>String(l?.listId)===String(id)).forEach(l=>(l.items||[]).forEach(x=>{const k=`${x.product}__${x.color||'SEM COR'}`;m.set(k,(m.get(k)||0)+Number(x.qty||0))}));return m};
function readyToArchive(list){if(!list?.id)return false;const sent=sentMap(list.id);return Object.values(list.items||{}).filter(x=>x?.product&&!EXCLUDED.has(String(x.product).trim().toUpperCase())).every(x=>Number(sent.get(`${x.product}__${x.color||'SEM COR'}`)||0)>=Number(x.total||0));}
function archiveList(list){if(!list?.id)return;if(!readyToArchive(list)){alert('Esta lista ainda possui itens de costura não enviados. Envie todos os itens pelo relatório de costura antes de arquivar.');return}if(!confirm(`Arquivar a lista "${list.name||'Lista'}"?\n\nOs relatórios de costura continuarão preservados em Arquivados.`))return;const lists=activeLists(),target=lists.find(x=>String(x?.id)===String(list.id));if(!target)return;save(ARCHIVE_KEY,[...archivedLists().filter(x=>String(x?.id)!==String(target.id)),{...target,archivedAt:new Date().toISOString()}]);save('almox-lists',lists.filter(x=>String(x?.id)!==String(target.id)));if(String(localStorage.getItem('almox-current')||'')===String(target.id))localStorage.removeItem('almox-current');location.reload()}
function openArchived(){let old=document.getElementById('workneo-archive-overlay');if(old)old.remove();const o=document.createElement('div');o.id='workneo-archive-overlay';o.innerHTML='<div class="wa-panel"><div class="wa-head"><div><small>WORKNEO · ALMOXARIFADO</small><h2>🗂️ Listas arquivadas</h2></div><button id="wa-close">×</button></div><div class="wa-body" id="wa-body"></div></div>';document.body.appendChild(o);o.onclick=e=>{if(e.target===o)o.remove()};o.querySelector('#wa-close').onclick=()=>o.remove();renderArchived(o.querySelector('#wa-body'))}
function renderArchived(body){const lists=archivedLists().sort((a,b)=>String(b.archivedAt||'').localeCompare(String(a.archivedAt||'')));if(!lists.length){body.innerHTML='<div class="wa-empty">Nenhuma lista arquivada.</div>';return}body.innerHTML=lists.map((l,i)=>'<div class="wa-card"><div><b>'+esc(l.name||'Lista')+'</b><small>'+Object.keys(l.items||{}).length+' combinações · '+total(l)+' unidades · arquivada em '+new Date(l.archivedAt).toLocaleDateString('pt-BR')+'</small></div><div class="wa-actions"><button data-restore="'+i+'">↩️ RESTAURAR</button><button class="danger" data-delete="'+i+'">🗑️ EXCLUIR</button></div></div>').join('');body.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{const l=lists[Number(b.dataset.restore)];if(!l||!confirm(`Restaurar a lista "${l.name||'Lista'}"?`))return;const clean={...l};delete clean.archivedAt;save('almox-lists',[...activeLists(),clean]);save(ARCHIVE_KEY,lists.filter(x=>String(x.id)!==String(l.id)));save('almox-current',String(l.id));location.reload()});body.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const l=lists[Number(b.dataset.delete)];if(!l||!confirm(`Excluir permanentemente a lista arquivada "${l.name||'Lista'}"?`))return;save(ARCHIVE_KEY,lists.filter(x=>String(x.id)!==String(l.id)));renderArchived(body)})}
function styleArchive(){if(document.getElementById('workneo-archive-style'))return;const s=document.createElement('style');s.id='workneo-archive-style';s.textContent='.wa-panel{max-width:900px;margin:40px auto;background:#fff;color:#172033;border-radius:20px;overflow:hidden;box-shadow:0 20px 60px #0008}.wa-head{display:flex;justify-content:space-between;align-items:center;padding:18px 20px;border-bottom:1px solid #e5e7eb}.wa-head h2{margin:4px 0}.wa-head button{border:0;border-radius:10px;background:#eef2f7;font-size:24px;width:40px;height:40px;cursor:pointer}.wa-body{padding:16px}.wa-card{display:flex;justify-content:space-between;gap:12px;align-items:center;border:1px solid #e1e5eb;border-radius:14px;padding:14px;margin-bottom:10px}.wa-card small{display:block;color:#667085;margin-top:5px}.wa-actions{display:flex;gap:7px;flex-wrap:wrap}.wa-actions button{border:0;border-radius:9px;padding:9px 11px;font-weight:800;cursor:pointer;background:#1769e0;color:#fff}.wa-actions .danger{background:#fee4e2;color:#b42318}.wa-empty{text-align:center;padding:35px;color:#667085}.wa-archive-current{background:#1769e0!important;color:#fff!important}.wa-archive-disabled{opacity:.55!important;cursor:not-allowed!important}#workneo-archive-overlay{position:fixed;inset:0;z-index:15000;background:#0008;overflow:auto;padding:16px;box-sizing:border-box}@media(max-width:700px){.wa-panel{margin:10px auto}.wa-card{display:block}.wa-actions{margin-top:10px}}';document.head.appendChild(s)}
function injectArchiveUI(){styleArchive();const quick=document.querySelector('.quick');const currentId=String(localStorage.getItem('almox-current')||'');const current=activeLists().find(x=>String(x?.id)===currentId);if(quick&&!quick.querySelector('.wa-archive-current')&&current){const b=document.createElement('button');b.className='wa-archive-current';b.textContent=readyToArchive(current)?'🗂️ ARQUIVAR LISTA':'🗂️ ARQUIVAR LISTA (APÓS COSTURA)';b.title=readyToArchive(current)?'Arquivar lista já enviada para costura':'Envie todos os itens de costura pelo relatório antes de arquivar';b.onclick=()=>archiveList(current);if(!readyToArchive(current))b.classList.add('wa-archive-disabled');quick.appendChild(b)}const nav=document.querySelector('.tabs');if(nav&&!nav.querySelector('.wa-open-archived')){const b=document.createElement('button');b.className='wa-open-archived';b.textContent='🗂️ Arquivadas';b.onclick=openArchived;nav.appendChild(b)}const cards=[...document.querySelectorAll('.list-card')];const lists=activeLists();cards.forEach((card,index)=>{if(card.querySelector('.wa-card-archive'))return;const list=lists[index];if(!list?.id||!readyToArchive(list))return;const b=document.createElement('button');b.className='wa-card-archive';b.textContent='🗂️';b.title='Arquivar lista enviada para costura';b.onclick=e=>{e.preventDefault();e.stopPropagation();archiveList(list)};card.appendChild(b)})}
function startArchiveUI(){injectArchiveUI();let n=0;const timer=setInterval(()=>{injectArchiveUI();if(++n>=30)clearInterval(timer)},500);const root=document.getElementById('root')||document.body;new MutationObserver(()=>injectArchiveUI()).observe(root,{childList:true,subtree:true})}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',startArchiveUI);else startArchiveUI();