import { TECHNICAL_SHEETS, EXCLUDED_SEWING_PRODUCTS } from './productionData.js';

const KEY='workneo-costureiras-relatorio-v1';
const ignored=new Set((EXCLUDED_SEWING_PRODUCTS||[]).map(x=>String(x).trim().toUpperCase()));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number.isInteger(Number(n))?String(Number(n)):Number(n||0).toFixed(2).replace(/\.00$/,'');
function lists(){try{return JSON.parse(localStorage.getItem('almox-lists')||'[]')}catch(_){return[]}}
function assignments(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(_){return[]}}
function save(v){localStorage.setItem(KEY,JSON.stringify(v))}
function listItems(list){return Object.values(list?.items||{}).filter(x=>x?.product&&!ignored.has(String(x.product).trim().toUpperCase())&&Number(x.total)>0)}
function orderOf(item,list){return item?.orderNumber??item?.numeroPedido??item?.pedido??item?.order??item?.numero??list?.orderNumber??list?.numeroPedido??list?.pedido??''}
function listLabel(list){return String(list?.name||list?.title||list?.nome||'Lista sem nome')}
function style(){if(document.getElementById('cs-integrated-style'))return;const s=document.createElement('style');s.id='cs-integrated-style';s.textContent=`
.csi-note{padding:13px 15px;background:#eef6ff;border:1px solid #c9defc;border-radius:14px;margin-bottom:14px;color:#174a8b;font-size:13px}.csi-form{display:grid;grid-template-columns:1.2fr 1.2fr 1fr .75fr 1fr 1fr;gap:9px;padding:15px;background:#f8fafc;border:1px solid #e2e7ef;border-radius:16px;margin-bottom:14px}.csi-field label{display:block;font-size:11px;font-weight:900;color:#667085;margin-bottom:5px}.csi-field select,.csi-field input{width:100%;box-sizing:border-box;border:1px solid #cfd6e2;border-radius:10px;background:#fff;padding:11px;font-size:14px;color:#172033}.csi-help{font-size:11px;color:#667085;margin-top:4px}.csi-send{border:0;border-radius:11px;background:#14804a;color:#fff;font-weight:900;padding:11px;cursor:pointer}.csi-send:disabled{opacity:.45}.csi-actions{display:flex;gap:9px;flex-wrap:wrap;margin-bottom:14px}.csi-btn{border:0;border-radius:11px;padding:11px 14px;background:#1769e0;color:#fff;font-weight:900}.csi-btn.secondary{background:#eef2f7;color:#172033}.csi-list{border:1px solid #e2e7ef;border-radius:16px;overflow:hidden}.csi-list h3{margin:0;padding:13px 15px;background:#f8fafc}.csi-row{display:grid;grid-template-columns:1.35fr 1.1fr .8fr .75fr 1fr auto;gap:8px;padding:11px 12px;border-top:1px solid #edf0f4;align-items:center;font-size:12px}.csi-badge{display:inline-block;padding:4px 8px;border-radius:999px;background:#eef2f7;font-weight:800}.csi-remove{border:0;border-radius:9px;background:#d92d20;color:#fff;font-weight:900;padding:8px}.csi-report{font-family:Arial,sans-serif;color:#101828;background:#fff}.csi-report-head{display:flex;justify-content:space-between;gap:15px;border-bottom:2px solid #172033;padding-bottom:10px;margin-bottom:10px}.csi-report-head h1{margin:0;font-size:22px}.csi-report-head small{color:#667085}.csi-summary{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:10px}.csi-card{padding:9px 12px;border:1px solid #dfe5ed;border-radius:10px;background:#f8fafc}.csi-table{width:100%;border-collapse:collapse;font-size:12px}.csi-table th,.csi-table td{border:1px solid #c8ced8;padding:6px;text-align:left}.csi-table th{background:#f1f4f8;font-weight:900}.csi-table td.num,.csi-table th.num{text-align:right}.csi-total{font-weight:900;background:#f8fafc}.csi-report-tools{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.csi-print{border:0;border-radius:10px;padding:10px 14px;background:#1769e0;color:#fff;font-weight:900}.csi-back{border:0;border-radius:10px;padding:10px 14px;background:#eef2f7;font-weight:900}
@media(max-width:700px){.csi-form{grid-template-columns:1fr 1fr}.csi-form .csi-field:first-child,.csi-form .csi-send{grid-column:1/-1}.csi-row{grid-template-columns:1fr 1fr}.csi-row .csi-remove{grid-column:1/-1}.csi-table{font-size:10px}.csi-table th,.csi-table td{padding:4px}}
@media print{body>*:not(#production-overlay){display:none!important}#production-overlay{display:block!important;position:static!important;padding:0!important;background:#fff!important}#production-panel{box-shadow:none!important;border-radius:0!important;min-height:0!important}.prod-head,.prod-tabs,.prod-toolbar,.prod-note{display:none!important}.prod-body{padding:0!important}.csi-report-tools{display:none!important}.csi-report{font-size:9px}.csi-table{font-size:9px}.csi-table th,.csi-table td{padding:3px}}
`;document.head.appendChild(s)}
function panel(){return document.getElementById('production-panel')}
function activate(tabName){const p=panel();if(!p)return; p.querySelectorAll('.prod-tab').forEach(t=>t.classList.toggle('active',String(t.dataset.tab||'')===tabName))}
function renderSelector(){const p=panel();if(!p)return;style();activate('costureiras');const ls=lists();const body=p.querySelector('.prod-body');if(!body)return;
let selectedListId='';let selectedProduct='';let selectedColor='';
body.innerHTML=`<div class="csi-note"><b>ABA COSTUREIRAS — LISTAS INTEGRADAS.</b> Agora você pode montar um único lote usando itens de várias listas. Escolha a <b>lista</b>, o <b>produto/cor</b>, informe o <b>Nº do pedido</b> e a costureira. Nada aqui altera a Aba 1.</div>
<div class="csi-actions"><button class="csi-btn" id="csi-report">📄 GERAR RELATÓRIO</button><button class="csi-btn secondary" id="csi-clear">🗑️ LIMPAR ENVIADOS</button></div>
<div class="csi-form">
<div class="csi-field"><label>LISTA</label><select id="csi-list"><option value="">Selecione a lista</option>${ls.map(l=>`<option value="${esc(l.id)}">${esc(listLabel(l))}</option>`).join('')}</select></div>
<div class="csi-field"><label>PRODUTO</label><select id="csi-product" disabled><option value="">Selecione o produto</option></select></div>
<div class="csi-field"><label>COR</label><select id="csi-color" disabled><option value="">Selecione a cor</option></select></div>
<div class="csi-field"><label>QUANTIDADE</label><input id="csi-qty" type="number" min="1" step="1" placeholder="0" disabled><div class="csi-help" id="csi-avail">Disponível: —</div></div>
<div class="csi-field"><label>Nº DO PEDIDO</label><input id="csi-order" type="text" placeholder="Ex.: 11000"><div class="csi-help">Pode ser diferente em cada item.</div></div>
<div class="csi-field"><label>COSTUREIRA</label><input id="csi-seam" type="text" placeholder="Nome"></div>
<button class="csi-send" id="csi-send" disabled>➜ ENVIAR PARA LOTE</button></div>
<div class="csi-list"><h3>ITENS DO LOTE / ENVIADOS PARA COSTURA</h3><div id="csi-rows"></div></div>`;
const selList=body.querySelector('#csi-list'),selProd=body.querySelector('#csi-product'),selColor=body.querySelector('#csi-color'),qty=body.querySelector('#csi-qty'),order=body.querySelector('#csi-order'),seam=body.querySelector('#csi-seam'),send=body.querySelector('#csi-send'),avail=body.querySelector('#csi-avail');
function currentList(){return ls.find(l=>String(l.id)===String(selList.value))||null}
function currentRows(){const l=currentList();return listItems(l)}
function currentItem(){return currentRows().find(x=>String(x.product)===String(selProd.value)&&String(x.color||'')===String(selColor.value||''))||null}
function used(item){return assignments().filter(a=>String(a.listId)===String(selList.value)&&String(a.product)===String(item?.product)&&String(a.color||'')===String(item?.color||'')).reduce((s,a)=>s+Number(a.qty||0),0)}
function refreshProduct(){const rows=currentRows();const names=[...new Set(rows.map(x=>x.product))].sort((a,b)=>String(a).localeCompare(String(b)));selProd.innerHTML='<option value="">Selecione o produto</option>'+names.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');selProd.disabled=!selList.value;selColor.innerHTML='<option value="">Selecione a cor</option>';selColor.disabled=true;qty.disabled=true;qty.value='';send.disabled=true;avail.textContent='Disponível: —';order.value=''}
function refreshColor(){const rows=currentRows().filter(x=>String(x.product)===String(selProd.value));const colors=[...new Set(rows.map(x=>x.color||'SEM COR'))].sort();selColor.innerHTML='<option value="">Selecione a cor</option>'+colors.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');selColor.disabled=!selProd.value;qty.disabled=true;qty.value='';send.disabled=true}
function refreshItem(){const item=currentItem();const available=item?Math.max(0,Number(item.total)-used(item)):0;qty.max=String(available);qty.disabled=!item||available<1;avail.textContent=`Disponível: ${fmt(available)} UN`;const suggested=item?orderOf(item,currentList()):'';if(!order.value&&suggested)order.value=String(suggested);check()}
function check(){const item=currentItem();const available=item?Math.max(0,Number(item.total)-used(item)):0;send.disabled=!item||!seam.value.trim()||!Number.isInteger(Number(qty.value))||Number(qty.value)<1||Number(qty.value)>available}
selList.onchange=()=>{selectedListId=selList.value;refreshProduct()};selProd.onchange=()=>{selectedProduct=selProd.value;refreshColor()};selColor.onchange=()=>{selectedColor=selColor.value;refreshItem()};qty.oninput=check;order.oninput=check;seam.oninput=check;
send.onclick=()=>{const l=currentList(),item=currentItem(),q=Number(qty.value);if(!l||!item||!seam.value.trim()||!Number.isInteger(q)||q<1||q>Math.max(0,Number(item.total)-used(item))){alert('Confira lista, produto, cor, quantidade e costureira.');return}const all=assignments();all.push({id:`${Date.now()}-${Math.random().toString(16).slice(2)}`,listId:l.id,listName:listLabel(l),product:item.product,color:item.color||'',qty:q,costureira:seam.value.trim(),orderNumber:String(order.value||orderOf(item,l)||'').trim(),createdAt:new Date().toISOString()});save(all);renderSelector()};
body.querySelector('#csi-report').onclick=()=>renderReport();
body.querySelector('#csi-clear').onclick=()=>{if(confirm('Limpar todos os itens enviados para o lote/relatório?')){save([]);renderSelector()}};
drawRows();
function drawRows(){const target=body.querySelector('#csi-rows');const a=assignments();if(!a.length){target.innerHTML='<div class="prod-empty">Nenhum item enviado. Você pode misturar várias listas no mesmo lote.</div>';return}target.innerHTML=a.map((x,i)=>`<div class="csi-row"><div><b>${esc(x.product)}</b><br><span class="csi-badge">${esc(x.color||'SEM COR')}</span></div><div><b>Lista:</b> ${esc(x.listName||'—')}</div><div><b>Pedido:</b> ${esc(x.orderNumber||'—')}</div><div><b>${fmt(x.qty)} UN</b></div><div><span class="csi-badge">${esc(x.costureira||'—')}</span></div><button class="csi-remove" data-i="${i}">REMOVER</button></div>`).join('');target.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const a2=assignments();a2.splice(Number(b.dataset.i),1);save(a2);renderSelector()})}
}
function renderReport(){const p=panel();if(!p)return;style();activate('relatorio');const body=p.querySelector('.prod-body');if(!body)return;const a=assignments().slice().sort((x,y)=>`${x.costureira}|${x.listName}|${x.orderNumber}|${x.product}|${x.color}`.localeCompare(`${y.costureira}|${y.listName}|${y.orderNumber}|${y.product}|${y.color}`));const total=a.reduce((s,x)=>s+Number(x.qty||0),0);const groups=new Map();a.forEach(x=>{const k=`${x.product}|${x.color||''}`;groups.set(k,(groups.get(k)||0)+Number(x.qty||0))});body.innerHTML=`<div class="csi-report-tools"><button class="csi-back" id="csi-back">← COSTUREIRAS</button><button class="csi-print" id="csi-print">🖨️ IMPRIMIR RELATÓRIO</button></div><div class="csi-report"><div class="csi-report-head"><div><small>WORKNEO • PRODUÇÃO</small><h1>Relatório de lote para costura</h1><small>Itens selecionados de várias listas e pedidos</small></div><div><b>Data:</b> ${new Date().toLocaleDateString('pt-BR')}<br><b>Total:</b> ${fmt(total)} peças</div></div><div class="csi-summary"><div class="csi-card"><b>LISTAS</b><br>${new Set(a.map(x=>x.listId)).size}</div><div class="csi-card"><b>PEDIDOS</b><br>${new Set(a.map(x=>x.orderNumber).filter(Boolean)).size}</div><div class="csi-card"><b>COSTUREIRAS</b><br>${new Set(a.map(x=>x.costureira).filter(Boolean)).size}</div><div class="csi-card"><b>PEÇAS</b><br>${fmt(total)}</div></div><table class="csi-table"><thead><tr><th>LISTA</th><th>Nº PEDIDO</th><th>PRODUTO</th><th>COR</th><th>COSTUREIRA</th><th class="num">QTD.</th></tr></thead><tbody>${a.length?a.map(x=>`<tr><td>${esc(x.listName||'—')}</td><td>${esc(x.orderNumber||'—')}</td><td>${esc(x.product)}</td><td>${esc(x.color||'SEM COR')}</td><td>${esc(x.costureira||'—')}</td><td class="num"><b>${fmt(x.qty)}</b></td></tr>`).join(''):'<tr><td colspan="6">Nenhum item enviado.</td></tr>'}<tr class="csi-total"><td colspan="5">TOTAL GERAL</td><td class="num">${fmt(total)}</td></tr></tbody></table><div style="margin-top:12px"><b>RESUMO POR PRODUTO (todas as cores)</b><table class="csi-table"><thead><tr><th>PRODUTO</th><th class="num">TOTAL DE PEÇAS</th></tr></thead><tbody>${[...groups.entries()].sort().map(([k,v])=>{const p=k.split('|')[0];return `<tr><td>${esc(p)}</td><td class="num"><b>${fmt(v)}</b></td></tr>`}).join('')}</tbody></table></div></div>`;body.querySelector('#csi-back').onclick=renderSelector;body.querySelector('#csi-print').onclick=()=>window.print()}
function hook(){const p=panel();if(!p)return;style();p.querySelectorAll('.prod-tab').forEach(tab=>{if(tab.dataset.csiIntegrated==='1')return;tab.dataset.csiIntegrated='1';tab.addEventListener('click',e=>{const txt=norm(tab.textContent);if(txt.includes('COSTUREIRAS')){e.preventDefault();e.stopImmediatePropagation();renderSelector()}else if(txt.includes('RELATÓRIO')){e.preventDefault();e.stopImmediatePropagation();renderReport()}},true)})}
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase()}
setInterval(hook,700);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook);else hook();
