import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
const PRODUCTS=["PORTA GARRAFA LITRÃO","PORTA GARRAFA 600","PORTA GARRAFA 600 SEM ZÍPER","PORTA ÁGUA E ISOTÔNICO","BOLSA DE MÃO","BOLSA MEIA LUA","BARMAT","BARMAT GRANDE","LANCHEIRA","BOLSA FEMININA","CASE CELULAR","CASE NOTEBOOK","CORRENTE PARA ÓCULOS","CASE TABLET","CARTEIRA FEMININA","COOLER TÉRMICO LATERAL","PORTA ESPUMANTE 975ML","ESTOJO","PORTA GARRAFA LONG NECK 355ML","LIXEIRA AUTOMOTIVA","PORTA LATA 350ML","PORTA LATA 473ML","PORTA LATA PALITO 269ML","PORTA LATA PALITO 350ML","KIT LUVA DE FORNO","MÁSCARA PROTETORA","MATEIRA","MATEIRA PEQUENA","MINI BAG GRANDE LATERAL","PORTA MOEDAS","MOCHILA INFANTIL","MOCHILA TÉRMICA","MOUSE PAD","MOUSE PAD GAMER","MUNHEQUEIRA","NECESSAIRE","NECESSAIRE GRANDE","POCHETE","PORTA COPOS","PROTETOR FACIAL","PORTA ÓCULOS","PORTA SQUEEZE","PORTA VINHO DUPLO","PORTA VINHO DUPLO C/ PORTA TAÇAS","PORTA VINHO SIMPLES","MOCHILA TRANSVERSAL","MINI BAG PEQUENA TRANSVERSAL","TAG PARA MALA","COOLER TÉRMICO GRANDE","COOLER TÉRMICO PEQUENO","TAPA OLHO","VISEIRA","LATA CAMISA","LONG CAMISA","CANGA DE PRAIA","CANGA DE PRAIA G","MARMITEIRA IMPERMEÁVEL","MOCHILA IMPERMEÁVEL","VISEIRA TURBANTE","ESTEIRA DE PRAIA","WINE CASE DELUXE","WINE BAG"];
const COLORS=["PRETO","ROYAL","MARINHO","VERMELHO","PINK","ROSA BEBÊ","VERDE","AMARELO","LILÁS","VERDE PALMEIRAS","BRANCO","CELESTE","LARANJA","VERDE ÁGUA","MARROM","CREME","BEGE","AZUL BEBÊ","CINZA"];
const SEAMSTRESSES=["ELENI","MARA","SANDRA","MIRIAN","MARINA","ADRIANA","DONA JOSI","JAMINA","COSTURA INTERNA"];
const LISTS_KEY='workneo-clean-lists-v1',REPORTS_KEY='workneo-clean-sewing-reports-v1';
const read=(k,f=[])=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return Array.isArray(v)?v:f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const uid=()=>Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);
const today=()=>new Date().toISOString().slice(0,10),n=v=>Math.max(0,Number(v)||0);
const fmtDate=v=>{if(!v)return '—';const [y,m,d]=String(v).split('-');return d&&m&&y?d+'/'+m+'/'+y:v};
const fmt=v=>Number(v||0).toLocaleString('pt-BR');
function App(){
const [tab,setTab]=useState('listas'),[lists,setLists]=useState(()=>read(LISTS_KEY)),[reports,setReports]=useState(()=>read(REPORTS_KEY));
const [selectedListId,setSelectedListId]=useState(''),[listName,setListName]=useState(''),[item,setItem]=useState({product:'',qty:'',color:'',pedido:''});
const [reportListId,setReportListId]=useState(''),[costureira,setCostureira]=useState(''),[reportDate,setReportDate]=useState(today()),[sendQty,setSendQty]=useState({}),[message,setMessage]=useState('');
const currentList=lists.find(x=>x.id===selectedListId)||null,reportList=lists.find(x=>x.id===reportListId)||null;
const saveLists=v=>{setLists(v);write(LISTS_KEY,v)},saveReports=v=>{setReports(v);write(REPORTS_KEY,v)};
const createList=()=>{const name=listName.trim()||'Lista '+new Date().toLocaleDateString('pt-BR'),l={id:uid(),name,createdAt:new Date().toISOString(),items:[]},v=[...lists,l];saveLists(v);setSelectedListId(l.id);setReportListId(l.id);setListName('');setMessage('Lista criada.')};
const addItem=()=>{if(!selectedListId||!item.product||n(item.qty)<=0){setMessage('Escolha a lista, o produto e uma quantidade maior que zero.');return}saveLists(lists.map(l=>l.id!==selectedListId?l:{...l,items:[...l.items,{id:uid(),product:item.product,qty:n(item.qty),color:item.color||'SEM COR',pedido:String(item.pedido||'').trim()}]}));setItem({product:'',qty:'',color:'',pedido:''});setMessage('Item adicionado à lista.')};
const removeItem=id=>saveLists(lists.map(l=>l.id!==selectedListId?l:{...l,items:l.items.filter(x=>x.id!==id)}));
const generateReport=()=>{if(!reportList){setMessage('Escolha uma lista no Relatório.');return}if(!costureira){setMessage('Escolha a costureira.');return}const selected=reportList.items.map(x=>{const q=Math.min(n(sendQty[x.id]),n(x.qty));return q>0?{...x,qty:q}:null}).filter(Boolean);if(!selected.length){setMessage('Informe pelo menos uma quantidade para enviar.');return}const r={id:uid(),listId:reportList.id,listName:reportList.name,date:reportDate||today(),costureira,createdAt:new Date().toISOString(),items:selected};saveReports([r,...reports]);const used=new Map(selected.map(x=>[x.id,x.qty]));saveLists(lists.map(l=>l.id!==reportList.id?l:{...l,items:l.items.map(x=>{const q=n(used.get(x.id));return q?{...x,qty:n(x.qty)-q}:x}).filter(x=>x.qty>0)}));setSendQty({});setMessage('Relatório salvo para '+costureira+' com '+fmt(selected.reduce((s,x)=>s+x.qty,0))+' peças.');setTab('relatorios')};
const totalReport=reportList?reportList.items.reduce((s,x)=>s+Math.min(n(sendQty[x.id]),n(x.qty)),0):0;
const totals=useMemo(()=>{const m={};for(const r of reports)m[r.costureira]=(m[r.costureira]||0)+r.items.reduce((s,x)=>s+n(x.qty),0);return m},[reports]);
const printReport=r=>{const html='<!doctype html><html><head><meta charset="utf-8"><title>Relatório de Costura</title><style>body{font-family:Arial;padding:28px;color:#111}h1{font-size:22px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:6px 24px;margin:18px 0}table{width:100%;border-collapse:collapse;margin-top:16px}th,td{border:1px solid #bbb;padding:8px;text-align:left}th{background:#eee}.total{font-size:18px;font-weight:700;margin-top:16px}</style></head><body><h1>WORKNEO · RELATÓRIO PARA COSTURA</h1><div class="meta"><div><b>Costureira:</b> '+r.costureira+'</div><div><b>Data:</b> '+fmtDate(r.date)+'</div><div><b>Lista:</b> '+r.listName+'</div></div><table><thead><tr><th>PRODUTO</th><th>QUANT.</th><th>COR</th><th>Nº PEDIDO</th></tr></thead><tbody>'+r.items.map(x=>'<tr><td>'+x.product+'</td><td>'+x.qty+'</td><td>'+x.color+'</td><td>'+(x.pedido||'—')+'</td></tr>').join('')+'</tbody></table><div class="total">QUANTIDADE DE PEÇAS: '+fmt(r.items.reduce((s,x)=>s+x.qty,0))+'</div></body></html>';const w=window.open('','_blank');if(!w){setMessage('Permita pop-ups para imprimir.');return}w.document.write(html);w.document.close();w.focus();setTimeout(()=>w.print(),250)};
const deleteReport=id=>{if(confirm('Apagar este relatório salvo?'))saveReports(reports.filter(r=>r.id!==id))};
return <div className="app"><header className="top"><div><div className="brand">WORKNEO</div><div className="subtitle">Separação → Relatório → Costura</div></div><div className="status">Dados locais</div></header>
<nav className="tabs"><button className={tab==='listas'?'active':''} onClick={()=>setTab('listas')}>📋 LISTAS</button><button className={tab==='relatorios'?'active':''} onClick={()=>setTab('relatorios')}>📄 RELATÓRIOS</button></nav>
{message&&<div className="message" onClick={()=>setMessage('')}>{message}</div>}
{tab==='listas'&&<main className="page"><section className="panel"><div className="section-head"><div><h2>LISTA DE SEPARAÇÃO</h2><p>Cadastre os produtos que serão enviados para costura. A lista é a origem dos relatórios.</p></div></div><div className="create-row"><input value={listName} onChange={e=>setListName(e.target.value)} placeholder="Nome da lista (ex.: 11207 espaço luz)"/><button onClick={createList}>+ NOVA LISTA</button></div><div className="list-grid">{lists.length===0?<div className="empty">Nenhuma lista criada.</div>:lists.map(l=><button key={l.id} className={'list-card '+(selectedListId===l.id?'selected':'')} onClick={()=>{setSelectedListId(l.id);setReportListId(l.id)}}><b>{l.name}</b><span>{l.items.length} itens · {fmt(l.items.reduce((s,x)=>s+n(x.qty),0))} peças</span></button>)}</div></section>
{currentList&&<section className="panel"><div className="section-head"><div><h2>{currentList.name}</h2><p>Estrutura da planilha: PRODUTO · QUANT. · COR · Nº PEDIDO.</p></div><div className="big-number">{fmt(currentList.items.reduce((s,x)=>s+n(x.qty),0))}<small>peças</small></div></div><div className="form-grid"><label>PRODUTO<select value={item.product} onChange={e=>setItem({...item,product:e.target.value})}><option value="">Selecione...</option>{PRODUCTS.map(p=><option key={p}>{p}</option>)}</select></label><label>QUANTIDADE<input type="number" min="1" value={item.qty} onChange={e=>setItem({...item,qty:e.target.value})}/></label><label>COR<select value={item.color} onChange={e=>setItem({...item,color:e.target.value})}><option value="">Selecione...</option>{COLORS.map(c=><option key={c}>{c}</option>)}</select></label><label>Nº PEDIDO<input value={item.pedido} onChange={e=>setItem({...item,pedido:e.target.value})} placeholder="Ex.: 11207"/></label></div><button className="primary" onClick={addItem}>+ ADICIONAR À LISTA</button><div className="table-wrap"><table><thead><tr><th>PRODUTO</th><th>QUANT.</th><th>COR</th><th>Nº PEDIDO</th><th></th></tr></thead><tbody>{currentList.items.length?currentList.items.map(x=><tr key={x.id}><td>{x.product}</td><td>{x.qty}</td><td>{x.color}</td><td>{x.pedido||'—'}</td><td><button className="danger" onClick={()=>removeItem(x.id)}>Excluir</button></td></tr>):<tr><td colSpan="5" className="empty">Esta lista ainda não possui itens.</td></tr>}</tbody></table></div></section>}</main>}
{tab==='relatorios'&&<main className="page"><section className="panel"><div className="section-head"><div><h2>GERAR RELATÓRIO PARA COSTURA</h2><p>O relatório é gerado <b>a partir da lista</b>. A tela de Lista apenas cadastra os itens.</p></div></div><div className="form-grid"><label>LISTA<select value={reportListId} onChange={e=>{setReportListId(e.target.value);setSendQty({})}}><option value="">Selecione a lista...</option>{lists.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>COSTUREIRA<select value={costureira} onChange={e=>setCostureira(e.target.value)}><option value="">Selecione...</option>{SEAMSTRESSES.map(s=><option key={s}>{s}</option>)}</select></label><label>DATA DO ENVIO<input type="date" value={reportDate} onChange={e=>setReportDate(e.target.value)}/></label></div>{reportList?<><div className="hint">Selecione a quantidade de cada linha. O Nº PEDIDO vem da própria lista e fica registrado no relatório.</div><div className="table-wrap"><table><thead><tr><th>ENVIAR</th><th>PRODUTO</th><th>DISPONÍVEL</th><th>QTD. ENVIO</th><th>COR</th><th>Nº PEDIDO</th></tr></thead><tbody>{reportList.items.length?reportList.items.map(x=><tr key={x.id}><td><input className="check" type="checkbox" checked={n(sendQty[x.id])>0} onChange={e=>setSendQty({...sendQty,[x.id]:e.target.checked?x.qty:0})}/></td><td>{x.product}</td><td>{x.qty}</td><td><input className="qty" type="number" min="0" max={x.qty} value={sendQty[x.id]??0} onChange={e=>setSendQty({...sendQty,[x.id]:Math.min(n(e.target.value),x.qty)})}/></td><td>{x.color}</td><td>{x.pedido||'—'}</td></tr>):<tr><td colSpan="6" className="empty">A lista está sem saldo para envio.</td></tr>}</tbody></table></div><div className="report-total">QUANTIDADE DE PEÇAS: <b>{fmt(totalReport)}</b></div><button className="primary large" onClick={generateReport}>📄 GERAR E SALVAR RELATÓRIO / ENVIAR PARA COSTURA</button></>:<div className="empty">Escolha uma lista para carregar os itens.</div>}</section>
<section className="panel"><div className="section-head"><div><h2>SOMATÓRIA POR COSTUREIRA</h2><p>Todos os relatórios salvos permanecem separados por envio e entram na soma.</p></div></div><div className="summary-grid">{SEAMSTRESSES.map(s=><div className="summary-card" key={s}><span>{s}</span><b>{fmt(totals[s]||0)}</b><small>peças enviadas</small></div>)}</div></section>
<section className="panel"><div className="section-head"><div><h2>RELATÓRIOS SALVOS</h2><p>Cada envio fica registrado individualmente.</p></div></div>{reports.length===0?<div className="empty">Nenhum relatório salvo.</div>:<div className="saved-list">{reports.map(r=><article className="saved" key={r.id}><div><b>{r.costureira}</b><span>{r.listName} · {fmtDate(r.date)}</span><span>{fmt(r.items.reduce((s,x)=>s+n(x.qty),0))} peças · {r.items.length} linhas</span></div><div className="actions"><button onClick={()=>printReport(r)}>🖨️ IMPRIMIR</button><button className="danger" onClick={()=>deleteReport(r.id)}>Excluir</button></div><details><summary>Ver itens</summary><div className="table-wrap"><table><thead><tr><th>PRODUTO</th><th>QTD.</th><th>COR</th><th>Nº PEDIDO</th></tr></thead><tbody>{r.items.map((x,i)=><tr key={i}><td>{x.product}</td><td>{x.qty}</td><td>{x.color}</td><td>{x.pedido||'—'}</td></tr>)}</tbody></table></div></details></article>)}</div>}</section></main>}
<footer>WORKNEO · reconstrução limpa · sem módulos antigos de costura.</footer></div>}
createRoot(document.getElementById('root')).render(<App/>);