import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{MATERIAL_RULES}from'./materialRules.js';
import'./styles.css';

const PRODUCTS=["PORTA GARRAFA LITRÃO","PORTA GARRAFA 600","PORTA GARRAFA 600 SEM ZÍPER","PORTA ÁGUA E ISOTÔNICO","BOLSA DE MÃO","BOLSA MEIA LUA","BARMAT","BARMAT GRANDE","LANCHEIRA","BOLSA FEMININA","CASE CELULAR","CASE NOTEBOOK","CORRENTE PARA ÓCULOS","CASE TABLET","CARTEIRA FEMININA","COOLER TÉRMICO LATERAL","PORTA ESPUMANTE 975ML","ESTOJO","PORTA GARRAFA LONG NECK 355ML","LIXEIRA AUTOMOTIVA","PORTA LATA 350ML","PORTA LATA 473ML","PORTA LATA PALITO 269ML","PORTA LATA PALITO 350ML","KIT LUVA DE FORNO","MÁSCARA PROTETORA","MATEIRA","MATEIRA PEQUENA","MINI BAG GRANDE LATERAL","PORTA MOEDAS","MOCHILA INFANTIL","MOCHILA TÉRMICA","MOUSE PAD","MOUSE PAD GAMER","MUNHEQUEIRA","NECESSAIRE","NECESSAIRE GRANDE","POCHETE","PORTA COPOS","PROTETOR FACIAL","PORTA ÓCULOS","PORTA SQUEEZE","PORTA VINHO DUPLO","PORTA VINHO DUPLO C/ PORTA TAÇAS","PORTA VINHO SIMPLES","MOCHILA TRANSVERSAL","MINI BAG PEQUENA TRANSVERSAL","TAG PARA MALA","COOLER TÉRMICO GRANDE","COOLER TÉRMICO PEQUENO","TAPA OLHO","VISEIRA","LATA CAMISA","LONG CAMISA","CANGA DE PRAIA","CANGA DE PRAIA G","MARMITEIRA IMPERMEÁVEL","MOCHILA IMPERMEÁVEL","VISEIRA TURBANTE","ESTEIRA DE PRAIA","WINE CASE DELUXE","WINE BAG"];
const COLORS=["PRETO","ROYAL","MARINHO","VERMELHO","PINK","ROSA BEBÊ","VERDE","AMARELO","LILÁS","VERDE PALMEIRAS","BRANCO","CELESTE","LARANJA","VERDE ÁGUA","MARROM","CREME","BEGE","AZUL BEBÊ","CINZA"];
const SEAMSTRESSES=["ELENI","MARA","SANDRA","MIRIAN","MARINA","ADRIANA","DONA JOSI","JAMINA","COSTURA INTERNA"];
const LISTS_KEY='workneo-clean-lists-v1',REPORTS_KEY='workneo-clean-sewing-reports-v1';
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();
const read=(k,f=[])=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return Array.isArray(v)?v:f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const uid=()=>Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);
const today=()=>new Date().toISOString().slice(0,10),n=v=>Math.max(0,Number(v)||0);
const fmt=v=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:2});
const fmtDate=v=>{if(!v)return'—';const[y,m,d]=String(v).split('-');return d&&m&&y?d+'/'+m+'/'+y:v};
const ruleMap=new Map(MATERIAL_RULES.map(([p,r])=>[norm(p),r]));
const MATERIAL_NAMES={fita_rigida:'FITA RÍGIDA',elastico:'ELÁSTICO',vies:'VIÉS',pompom:'POMPOM',elastico_rabo:'ELÁSTICO RABO DE GATO',cordas:'CORDAS POLIÉSTER',elastico_ff:'ELÁSTICO FF',gorgurao:'GORGURÃO',poliester:'POLIÉSTER',cadaraço:'CADARÇO',mosquetao:'MOSQUETÃO',fecho:'FECHO',passador:'PASSADOR',meia_argola:'MEIA ARGOLA',regulador:'REGULADOR FOCINHO DE PORCO',etiqueta:'ETIQUETA',velcro:'VELCRO',borracha_elastica:'BORRACHA ELÁSTICO',espuma:'ESPUMA',plastico_transparente:'PLÁSTICO TRANSPARENTE',forro_termico:'FORRO TÉRMICO',forro_impermeavel:'FORRO IMPERMEÁVEL',plastico_duro:'PLÁSTICO DURO',tela_bolso:'TELA DE BOLSO',forro_matelace:'FORRO MATELACÊ'};
const UNIT_KINDS=new Set(['mosquetao','fecho','passador','meia_argola','regulador','etiqueta','borracha_elastica','espuma','plastico_transparente','forro_termico','forro_impermeavel','plastico_duro','tela_bolso','forro_matelace']);
const HARDWARE=new Set(['mosquetao','fecho','passador','meia_argola','regulador']);
const NO_COLOR=new Set(['etiqueta','velcro','borracha_elastica','espuma','plastico_transparente','forro_termico','forro_impermeavel','plastico_duro','tela_bolso','forro_matelace']);
const materialLabel=(kind,param,val)=>{if(kind==='linha')return{label:'LINHA — '+String(param).toUpperCase(),spec:'',unit:'M',raw:val,convert:false};if(kind==='ziper3'||kind==='ziper5')return{label:'ZÍPER Nº '+(kind==='ziper3'?'3':'5'),spec:param,unit:'UN',raw:val,convert:false};if(UNIT_KINDS.has(kind))return{label:MATERIAL_NAMES[kind]||kind.toUpperCase(),spec:param==='UNI'?'':param,unit:'UN',raw:val,convert:false};if(param==='largura')return null;return{label:MATERIAL_NAMES[kind]||kind.toUpperCase(),spec:param.toUpperCase()+' / PEÇA',unit:'M',raw:val,convert:true}};
const calculateMaterials=items=>{const out=[];for(const item of items){const rules=ruleMap.get(norm(item.product))||[];const pending={};for(const[kind,param,val]of rules){if(param==='largura'){pending[kind]=val;continue}const meta=materialLabel(kind,param,val);if(!meta)continue;const qty=n(item.qty)*n(val)/(meta.convert?100:1);let spec=meta.spec;if(pending[kind]!=null)spec='LARG. '+pending[kind]+' · '+spec;const color=UNIT_KINDS.has(kind)?(param||'SEM COR'):(HARDWARE.has(kind)?(param||'SEM COR'):(item.color||'SEM COR'));out.push({key:[meta.label,spec,meta.unit,color].join('|'),material:meta.label,spec,unit:meta.unit,color,qty});}}const map=new Map();for(const x of out){const old=map.get(x.key);if(old)old.qty+=x.qty;else map.set(x.key,{...x})}return[...map.values()].sort((a,b)=>a.material.localeCompare(b.material)||a.spec.localeCompare(b.spec)||a.color.localeCompare(b.color))};
const groupProducts=items=>{const m=new Map();for(const x of items){const k=norm(x.product);let g=m.get(k);if(!g){g={product:x.product,qty:0,colors:new Set(),orders:new Set()};m.set(k,g)}g.qty+=n(x.qty);if(x.color)g.colors.add(x.color);if(x.pedido)g.orders.add(x.pedido)}return[...m.values()].map(x=>({...x,colors:[...x.colors],orders:[...x.orders]})).sort((a,b)=>a.product.localeCompare(b.product))};
const materialRows=(materials,filter)=>materials.filter(x=>filter(x));
const matrixHtml=(materials,title)=>{const rows=materialRows(materials,x=>!NO_COLOR.has(norm(x.material).toLowerCase())&&!HARDWARE.has(norm(x.material).toLowerCase()));const colors=[...new Set(rows.map(x=>x.color).filter(Boolean))];if(!rows.length)return'<h3>'+title+'</h3><p>Nenhum material.</p>';const keys=[...new Set(rows.map(x=>x.material+'|'+x.spec+'|'+x.unit))];const body=keys.map(k=>{const[a,b,u]=k.split('|');const vals=colors.map(c=>rows.filter(x=>x.material===a&&x.spec===b&&x.unit===u&&x.color===c).reduce((s,x)=>s+x.qty,0));const total=vals.reduce((s,v)=>s+v,0);return'<tr><td>'+a+'</td><td>'+b+(u?' ('+u+')':'')+'</td>'+vals.map(v=>'<td>'+fmt(v)+'</td>').join('')+'<td>'+fmt(total)+'</td></tr>'}).join('');return'<h3>'+title+'</h3><table><thead><tr><th>MATERIAL</th><th>ESPECIFICAÇÃO</th>'+colors.map(c=>'<th>'+c+'</th>').join('')+'<th>TOTAL</th></tr></thead><tbody>'+body+'</tbody></table>';};
const simpleMaterialHtml=(materials,title,fn)=>{const rows=materialRows(materials,fn);if(!rows.length)return'<h3>'+title+'</h3><p>Nenhum material.</p>';const map=new Map();for(const x of rows){const k=x.material+'|'+x.spec+'|'+x.unit;map.set(k,(map.get(k)||0)+x.qty)}const body=[...map].map(([k,v])=>{const[a,b,u]=k.split('|');return'<tr><td>'+a+'</td><td>'+b+'</td><td>'+fmt(v)+' '+u+'</td></tr>'}).join('');return'<h3>'+title+'</h3><table><thead><tr><th>MATERIAL</th><th>ESPECIFICAÇÃO</th><th>TOTAL</th></tr></thead><tbody>'+body+'</tbody></table>};
function App(){
const[tab,setTab]=useState('listas'),[lists,setLists]=useState(()=>read(LISTS_KEY)),[reports,setReports]=useState(()=>read(REPORTS_KEY));
const[selectedListId,setSelectedListId]=useState(''),[listName,setListName]=useState(''),[item,setItem]=useState({product:'',qty:'',color:'',pedido:''});
const[reportListId,setReportListId]=useState(''),[costureira,setCostureira]=useState(''),[reportDate,setReportDate]=useState(today()),[sendQty,setSendQty]=useState({}),[message,setMessage]=useState('');
const currentList=lists.find(x=>x.id===selectedListId)||null,reportList=lists.find(x=>x.id===reportListId)||null;
const saveLists=v=>{setLists(v);write(LISTS_KEY,v)},saveReports=v=>{setReports(v);write(REPORTS_KEY,v)};
const createList=()=>{const name=listName.trim()||'Lista '+new Date().toLocaleDateString('pt-BR'),l={id:uid(),name,createdAt:new Date().toISOString(),items:[]},v=[...lists,l];saveLists(v);setSelectedListId(l.id);setReportListId(l.id);setListName('');setMessage('Lista criada.')};
const addItem=()=>{if(!selectedListId||!item.product||n(item.qty)<=0){setMessage('Escolha a lista, o produto e uma quantidade maior que zero.');return}saveLists(lists.map(l=>l.id!==selectedListId?l:{...l,items:[...l.items,{id:uid(),product:item.product,qty:n(item.qty),color:item.color||'SEM COR',pedido:String(item.pedido||'').trim()}]}));setItem({product:'',qty:'',color:'',pedido:''});setMessage('Item adicionado à lista.')};
const removeItem=id=>saveLists(lists.map(l=>l.id!==selectedListId?l:{...l,items:l.items.filter(x=>x.id!==id)}));
const generateReport=()=>{if(!reportList){setMessage('Escolha uma lista no Relatório.');return}if(!costureira){setMessage('Escolha a costureira.');return}const selected=reportList.items.map(x=>{const q=Math.min(n(sendQty[x.id]),n(x.qty));return q>0?{...x,qty:q}:null}).filter(Boolean);if(!selected.length){setMessage('Informe pelo menos uma quantidade para enviar.');return}const grouped=groupProducts(selected),materials=calculateMaterials(selected),r={id:uid(),listId:reportList.id,listName:reportList.name,date:reportDate||today(),costureira,createdAt:new Date().toISOString(),items:selected,groupedProducts:grouped,materials};saveReports([r,...reports]);const used=new Map(selected.map(x=>[x.id,x.qty]));saveLists(lists.map(l=>l.id!==reportList.id?l:{...l,items:l.items.map(x=>{const q=n(used.get(x.id));return q?{...x,qty:n(x.qty)-q}:x}).filter(x=>x.qty>0)}));setSendQty({});setMessage('Relatório salvo: '+fmt(selected.reduce((s,x)=>s+x.qty,0))+' peças e '+fmt(materials.length)+' materiais calculados.');setTab('relatorios')};
const totalReport=reportList?reportList.items.reduce((s,x)=>s+Math.min(n(sendQty[x.id]),n(x.qty)),0):0;
const totals=useMemo(()=>{const m={};for(const r of reports)m[r.costureira]=(m[r.costureira]||0)+r.items.reduce((s,x)=>s+n(x.qty),0);return m},[reports]);
const printReport=(r,mode='completo')=>{const grouped=r.groupedProducts||groupProducts(r.items||[]),materials=r.materials||calculateMaterials(r.items||[]);const productsHtml='<h2>1. PRODUTOS AGRUPADOS NO ENVIO</h2><table><thead><tr><th>PRODUTO</th><th>QUANTIDADE</th><th>CORES</th><th>Nº PEDIDOS</th></tr></thead><tbody>'+grouped.map(x=>'<tr><td>'+x.product+'</td><td>'+fmt(x.qty)+'</td><td>'+x.colors.join(', ')+'</td><td>'+x.orders.join(', ')||'—'+'</td></tr>').join('')+'</tbody></table><div class="total">TOTAL DE PEÇAS: '+fmt((r.items||[]).reduce((s,x)=>s+n(x.qty),0))+'</div>';const materialsHtml='<h2>2. MATERIAIS PARA COSTURA</h2>'+matrixHtml(materials,'MATERIAIS POR COR')+simpleMaterialHtml(materials,'FERRAGENS E REGULADORES',x=>HARDWARE.has(norm(x.material).toLowerCase()))+simpleMaterialHtml(materials,'MATERIAIS SEM COR',x=>NO_COLOR.has(norm(x.material).toLowerCase()));const html='<!doctype html><html><head><meta charset="utf-8"><title>WORKNEO · Relatório</title><style>@page{size:A4 landscape;margin:12mm}body{font-family:Arial,sans-serif;color:#111;font-size:11px}h1{font-size:21px;margin:0 0 4px}h2{font-size:14px;margin:20px 0 7px}h3{font-size:12px;margin:14px 0 6px}.meta{display:grid;grid-template-columns:repeat(4,1fr);gap:5px 14px;margin:12px 0 14px}.meta div{border-bottom:1px solid #bbb;padding:5px 0}table{width:100%;border-collapse:collapse;margin:5px 0 12px}th,td{border:1px solid #777;padding:5px 6px;text-align:left}th{background:#ddd}td:nth-child(n+2){text-align:center}.total{font-weight:700;font-size:13px;margin:6px 0}.note{font-size:9px;color:#555;margin-top:15px}.print-only{display:block}</style></head><body><h1>WORKNEO · RELATÓRIO DE MATERIAIS PARA COSTURA</h1><div class="meta"><div><b>COSTUREIRA</b><br>'+r.costureira+'</div><div><b>LISTA</b><br>'+r.listName+'</div><div><b>DATA DA SEPARAÇÃO</b><br>'+fmtDate(r.date)+'</div><div><b>QUANTIDADE DE PEÇAS</b><br>'+fmt((r.items||[]).reduce((s,x)=>s+n(x.qty),0))+'</div></div>'+(mode==='pecas'?productsHtml:mode==='materiais'?materialsHtml:productsHtml+materialsHtml)+'<div class="note">Materiais calculados exclusivamente a partir das fichas técnicas da planilha FICHA SEPARAÇÃO 2026. A cor não encontrada na ficha usa a mesma regra técnica do produto, pois o processo de fabricação permanece o mesmo.</div></body></html>';const w=window.open('','_blank');if(!w){setMessage('Permita pop-ups para imprimir.');return}w.document.write(html);w.document.close();w.focus();setTimeout(()=>w.print(),250)};
const deleteReport=id=>{if(confirm('Apagar este relatório salvo?'))saveReports(reports.filter(r=>r.id!==id))};
return <div className="app"><header className="top"><div><div className="brand">WORKNEO</div><div className="subtitle">Lista → Relatório → Materiais → Costura</div></div><div className="status">Ficha técnica ativa</div></header>
<nav className="tabs"><button className={tab==='listas'?'active':''} onClick={()=>setTab('listas')}>📋 LISTAS</button><button className={tab==='relatorios'?'active':''} onClick={()=>setTab('relatorios')}>📄 RELATÓRIOS</button></nav>
{message&&<div className="message" onClick={()=>setMessage('')}>{message}</div>}
{tab==='listas'&&<main className="page"><section className="panel"><div className="section-head"><div><h2>LISTA DE SEPARAÇÃO</h2><p>A lista recebe os produtos do pedido. O cálculo de materiais acontece somente no Relatório.</p></div></div><div className="create-row"><input value={listName} onChange={e=>setListName(e.target.value)} placeholder="Nome da lista (ex.: 11207 espaço luz)"/><button onClick={createList}>+ NOVA LISTA</button></div><div className="list-grid">{lists.length===0?<div className="empty">Nenhuma lista criada.</div>:lists.map(l=><button key={l.id} className={'list-card '+(selectedListId===l.id?'selected':'')} onClick={()=>{setSelectedListId(l.id);setReportListId(l.id)}}><b>{l.name}</b><span>{l.items.length} linhas · {fmt(l.items.reduce((s,x)=>s+n(x.qty),0))} peças</span></button>)}</div></section>
{currentList&&<section className="panel"><div className="section-head"><div><h2>{currentList.name}</h2><p>PRODUTO · QUANT. · COR · Nº PEDIDO</p></div><div className="big-number">{fmt(currentList.items.reduce((s,x)=>s+n(x.qty),0))}<small>peças</small></div></div><div className="form-grid"><label>PRODUTO<select value={item.product} onChange={e=>setItem({...item,product:e.target.value})}><option value="">Selecione...</option>{PRODUCTS.map(p=><option key={p}>{p}</option>)}</select></label><label>QUANTIDADE<input type="number" min="1" value={item.qty} onChange={e=>setItem({...item,qty:e.target.value})}/></label><label>COR<select value={item.color} onChange={e=>setItem({...item,color:e.target.value})}><option value="">Selecione...</option>{COLORS.map(c=><option key={c}>{c}</option>)}</select></label><label>Nº PEDIDO<input value={item.pedido} onChange={e=>setItem({...item,pedido:e.target.value})} placeholder="Ex.: 11207"/></label></div><button className="primary" onClick={addItem}>+ ADICIONAR À LISTA</button><div className="table-wrap"><table><thead><tr><th>PRODUTO</th><th>QUANT.</th><th>COR</th><th>Nº PEDIDO</th><th></th></tr></thead><tbody>{currentList.items.length?currentList.items.map(x=><tr key={x.id}><td>{x.product}</td><td>{x.qty}</td><td>{x.color}</td><td>{x.pedido||'—'}</td><td><button className="danger" onClick={()=>removeItem(x.id)}>Excluir</button></td></tr>):<tr><td colSpan="5" className="empty">Esta lista ainda não possui itens.</td></tr>}</tbody></table></div></section>}</main>}
{tab==='relatorios'&&<main className="page"><section className="panel"><div className="section-head"><div><h2>GERAR RELATÓRIO A PARTIR DA LISTA</h2><p>Escolha a lista, a costureira e o envio. A ficha técnica calcula automaticamente zíperes, etiquetas, fitas, linhas e demais materiais.</p></div></div><div className="form-grid"><label>LISTA<select value={reportListId} onChange={e=>{setReportListId(e.target.value);setSendQty({})}}><option value="">Selecione a lista...</option>{lists.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>COSTUREIRA<select value={costureira} onChange={e=>setCostureira(e.target.value)}><option value="">Selecione...</option>{SEAMSTRESSES.map(s=><option key={s}>{s}</option>)}</select></label><label>DATA DO ENVIO<input type="date" value={reportDate} onChange={e=>setReportDate(e.target.value)}/></label></div>{reportList?<><div className="hint">Você pode misturar cores e números de pedido. Na hora do relatório, produtos iguais são agrupados; a ficha técnica é aplicada por produto. Uma cor nova continua usando a mesma ficha do produto.</div><div className="table-wrap"><table><thead><tr><th>ENVIAR</th><th>PRODUTO</th><th>DISPONÍVEL</th><th>QTD. ENVIO</th><th>COR</th><th>Nº PEDIDO</th></tr></thead><tbody>{reportList.items.length?reportList.items.map(x=><tr key={x.id}><td><input className="check" type="checkbox" checked={n(sendQty[x.id])>0} onChange={e=>setSendQty({...sendQty,[x.id]:e.target.checked?x.qty:0})}/></td><td>{x.product}</td><td>{x.qty}</td><td><input className="qty" type="number" min="0" max={x.qty} value={sendQty[x.id]??0} onChange={e=>setSendQty({...sendQty,[x.id]:Math.min(n(e.target.value),x.qty)})}/></td><td>{x.color}</td><td>{x.pedido||'—'}</td></tr>):<tr><td colSpan="6" className="empty">A lista está sem saldo para envio.</td></tr>}</tbody></table></div><div className="report-total">QUANTIDADE DE PEÇAS: <b>{fmt(totalReport)}</b></div><button className="primary large" onClick={generateReport}>📄 GERAR E SALVAR RELATÓRIO</button></>:<div className="empty">Escolha uma lista para carregar os itens.</div>}</section>
<section className="panel"><div className="section-head"><div><h2>SOMATÓRIA POR COSTUREIRA</h2><p>A soma considera todos os relatórios já salvos, sem duplicar o mesmo envio.</p></div></div><div className="summary-grid">{SEAMSTRESSES.map(s=><div className="summary-card" key={s}><span>{s}</span><b>{fmt(totals[s]||0)}</b><small>peças enviadas</small></div>)}</div></section>
<section className="panel"><div className="section-head"><div><h2>RELATÓRIOS SALVOS</h2><p>Cada envio permanece individual e pode gerar os dois relatórios.</p></div></div>{reports.length===0?<div className="empty">Nenhum relatório salvo.</div>:<div className="saved-list">{reports.map(r=><article className="saved" key={r.id}><div><b>{r.costureira}</b><span>{r.listName} · {fmtDate(r.date)}</span><span>{fmt(r.items.reduce((s,x)=>s+n(x.qty),0))} peças · {r.groupedProducts?.length||groupProducts(r.items).length} produtos agrupados</span></div><div className="actions"><button onClick={()=>printReport(r,'pecas')}>📦 PEÇAS AGRUPADAS</button><button onClick={()=>printReport(r,'materiais')}>🧵 MATERIAIS</button><button className="primary" onClick={()=>printReport(r,'completo')}>📄 COMPLETO</button><button className="danger" onClick={()=>deleteReport(r.id)}>Excluir</button></div><details><summary>Ver produtos enviados</summary><div className="table-wrap"><table><thead><tr><th>PRODUTO</th><th>QTD.</th><th>COR</th><th>Nº PEDIDO</th></tr></thead><tbody>{r.items.map((x,i)=><tr key={i}><td>{x.product}</td><td>{x.qty}</td><td>{x.color}</td><td>{x.pedido||'—'}</td></tr>)}</tbody></table></div></details></article>)}</div>}</section></main>}
<footer>WORKNEO · ficha técnica baseada na FICHA SEPARAÇÃO 2026 · cálculo no relatório</footer></div>}
createRoot(document.getElementById('root')).render(<App/>);