export const TECHNICAL_SHEETS = {
  "PORTA GARRAFA LITRÃO": { linhaZigM: 500, linhaRetaM: 200, ziper30CM: 1, vies: { largura: null, cmPeca: 30 }, etiqueta: 1 },
  "PORTA GARRAFA 600": { linhaZigM: 600, linhaRetaM: 200, ziper30CM: 1, vies: { largura: null, cmPeca: 25 }, etiqueta: 1 },
  "PORTA GARRAFA 600 SEM ZÍPER": {},
  "PORTA ÁGUA E ISOTÔNICO": { linhaZigM: 350, linhaRetaM: 200, ziper25CM: 1, vies: { largura: 0.23, cmPeca: 25 }, poliester: { largura: null, cmPeca: 150 }, cadarco: { largura: null, cmPeca: 6 }, mosquetao: { PRETO: 1 }, fecho: { PRETO: 1 }, passador: { PRETO: 1 }, etiqueta: 1 },
  "BOLSA DE MÃO": { linhaRetaM: 600, ziper35CM: 1, fitaRigida: { largura: null, cmPeca: 130 }, poliester: { largura: null, cmPeca: 150 }, cadarco: { largura: null, cmPeca: 15 }, mosquetao: { PRETO: 2 }, passador: { PRETO: 1 }, etiqueta: 1 },
  "BOLSA MEIA LUA": { linhaZigM: 1000, linhaRetaM: 1000, ziper30CM: 1, fitaRigida: { largura: null, cmPeca: 220 }, etiqueta: 1 },
  "BARMAT": {},
  "BARMAT GRANDE": {},
  "LANCHEIRA": { linhaZigM: 800, linhaRetaM: 500, ziper40CM: 1, fitaRigida: { largura: null, cmPeca: 160 }, poliester: { largura: null, cmPeca: 150 }, cadarco: { largura: null, cmPeca: 15 }, mosquetao: { PRETO: 2 }, passador: { PRETO: 1 }, etiqueta: 1 },
  "BOLSA FEMININA": { linhaZigM: 1.5, linhaRetaM: 12, ziper50CM: 1, fitaRigida: { largura: 2.03, cmPeca: 415 }, etiqueta: 1 },
  "CASE CELULAR": { linhaRetaM: 300, ziper30CM: 1, gorgurao: { largura: null, cmPeca: 30 }, etiqueta: 1 },
  "CASE NOTEBOOK": { linhaRetaM: 500, ziper50CM: 1, fitaRigida: { largura: null, cmPeca: 130 }, poliester: { largura: null, cmPeca: 150 }, cadarco: { largura: null, cmPeca: 15 }, mosquetao: { PRETO: 2 }, passador: { PRETO: 1 }, etiqueta: 1 },
  "CORRENTE PARA ÓCULOS": {},
  "CASE TABLET": { linhaRetaM: 600, ziper35CM: 1, fitaRigida: { largura: null, cmPeca: 120 }, poliester: { largura: null, cmPeca: 150 }, cadarco: { largura: null, cmPeca: 15 }, mosquetao: { PRETO: 2 }, passador: { PRETO: 1 }, etiqueta: 1 },
  "CARTEIRA FEMININA": { linhaRetaM: 300, ziper50CM: 1, fitaRigida: { largura: 2.2, cmPeca: 170 }, gorgurao: { largura: 1.03, cmPeca: 30 }, etiqueta: 1 },
  "COOLER TÉRMICO LATERAL": { linhaRetaM: 600, ziper80CM: 1, fitaRigida: { largura: null, cmPeca: 460 }, poliester: { largura: null, cmPeca: 180 }, mosquetao: { NIQUELADO: 2 }, passador: { NIQUELADO: 1 }, meiaArgola: { NIQUELADO: 2 }, etiqueta: 1 },
  "PORTA ESPUMANTE 975ML": { linhaZigM: 500, linhaRetaM: 200, ziper35CM: 1, etiqueta: 1 },
  "ESTOJO": { linhaRetaM: 400, ziper35CM: 1, cadarco: { largura: null, cmPeca: 8 }, etiqueta: 1 },
  "PORTA GARRAFA LONG NECK 355ML": { linhaZigM: 400, linhaRetaM: 200, ziper25CM: 1, vies: { largura: 0.23, cmPeca: 30 }, etiqueta: 1 },
  "LIXEIRA AUTOMOTIVA": { linhaZigM: 360, linhaRetaM: 200, fitaRigida: { largura: 2.05, cmPeca: 65 }, etiqueta: 1 },
  "PORTA LATA 350ML": { linhaZigM: 200, linhaRetaM: 100, elastico: { largura: null, cmPeca: 25 }, etiqueta: 1 },
  "PORTA LATA 473ML": { linhaZigM: 200, linhaRetaM: 100, elastico: { largura: null, cmPeca: 25 }, etiqueta: 1 },
  "PORTA LATA PALITO 269ML": { linhaZigM: 500, linhaRetaM: 200, elastico: { largura: null, cmPeca: 30 }, etiqueta: 1 },
  "PORTA LATA PALITO 350ML": { linhaZigM: 500, linhaRetaM: 200, elastico: { largura: null, cmPeca: 30 }, etiqueta: 1 },
  "KIT LUVA DE FORNO": { linhaZigM: 300, linhaRetaM: 200, vies: { largura: null, cmPeca: 48 }, etiqueta: 1 },
  "MÁSCARA PROTETORA": {},
  "MATEIRA": { linhaZigM: 620, linhaRetaM: 1000, fitaRigida: { largura: 2.03, cmPeca: 230 }, elastico: { largura: 2.03, cmPeca: 145 }, etiqueta: 1 },
  "MATEIRA PEQUENA": { linhaZigM: 620, linhaRetaM: 900, fitaRigida: { largura: 2.03, cmPeca: 230 }, elastico: { largura: 2.03, cmPeca: 75 }, etiqueta: 1 },
  "MINI BAG GRANDE LATERAL": { linhaRetaM: 700, ziper30CM: 1, ziper35CM: 1, poliester: { largura: null, cmPeca: 170 }, passador: { PRETO: 3 }, etiqueta: 1, borrachaElastico: 1 },
  "PORTA MOEDAS": { linhaRetaM: 300, ziper20CM: 1, cadarco: { largura: null, cmPeca: 7 }, etiqueta: 1 },
  "MOCHILA INFANTIL": { linhaRetaM: 800, ziper50CM: 1, fitaRigida: { largura: null, cmPeca: 160 }, poliester: { largura: null, cmPeca: 150 }, passador: { PRETO: 4 }, etiqueta: 1 },
  "MOCHILA TÉRMICA": { linhaZigM: 2000, linhaRetaM: 3000, ziper50CM: 1, fitaRigida: { largura: null, cmPeca: 580 }, poliester: { largura: null, cmPeca: 120 }, passador: { PRETO: 4 }, etiqueta: 1 },
  "MOUSE PAD": {},
  "MOUSE PAD GAMER": {},
  "MUNHEQUEIRA": { linhaRetaM: 300, elastico: { largura: null, cmPeca: 60 }, etiqueta: 1 },
  "NECESSAIRE": { linhaRetaM: 300, ziper35CM: 1, cadarco: { largura: null, cmPeca: 7 }, etiqueta: 1 },
  "NECESSAIRE GRANDE": { linhaRetaM: 200, ziper50CM: 1, fitaRigida: { largura: null, cmPeca: 60 }, cadarco: { largura: null, cmPeca: 7 }, etiqueta: 1 },
  "POCHETE": { linhaRetaM: 400, ziper30CM: 1, ziper35CM: 1, fitaRigida: { largura: 2.2, cmPeca: 110 }, poliester: { largura: null, cmPeca: 150 }, fecho: { PRETO: 1 }, passador: { PRETO: 1 }, etiqueta: 1, borrachaElastico: 1 },
  "PORTA COPOS": {},
  "PROTETOR FACIAL": { velcro: 8, espuma: 15, plasticoTransparente: 1 },
  "PORTA ÓCULOS": { linhaZigM: 300, linhaRetaM: 200, ziper30CM: 1, etiqueta: 1 },
  "PORTA SQUEEZE": { linhaZigM: 300, linhaRetaM: 100, elastico: { largura: null, cmPeca: 25 }, poliester: { largura: 2.2, cmPeca: 150 }, mosquetao: { PRETO: 1 }, fecho: { PRETO: 1 }, passador: { PRETO: 1 }, etiqueta: 1, borrachaElastico: 1 },
  "PORTA VINHO DUPLO": { linhaZigM: 1000, linhaRetaM: 500, fitaRigida: { largura: null, cmPeca: 150 }, etiqueta: 1 },
  "PORTA VINHO DUPLO C/ PORTA TAÇAS": { linhaZigM: 1000, linhaRetaM: 500, ziper50CM: 1, fitaRigida: { largura: null, cmPeca: 150 }, elastico: { largura: null, cmPeca: 20 }, poliester: { largura: null, cmPeca: 150 }, cadarco: { largura: null, cmPeca: 15 }, mosquetao: { PRETO: 2 }, passador: { PRETO: 1 }, etiqueta: 1 },
  "PORTA VINHO SIMPLES": { linhaZigM: 800, linhaRetaM: 300, fitaRigida: { largura: null, cmPeca: 115 }, etiqueta: 1 },
  "MOCHILA TRANSVERSAL": { ziper30CM: 1, ziper80CM: 1, fitaRigida: { largura: null, cmPeca: 70 }, poliester: { largura: null, cmPeca: 160 }, cadarco: { largura: null, cmPeca: 7 }, fecho: { PRETO: 2 }, passador: { PRETO: 1 }, etiqueta: 1, borrachaElastico: 1 },
  "MINI BAG PEQUENA TRANSVERSAL": { linhaRetaM: 300, ziper25CM: 1, ziper30CM: 1, poliester: { largura: null, cmPeca: 160 }, fecho: { PRETO: 1 }, passador: { PRETO: 1 }, etiqueta: 1, borrachaElastico: 1 },
  "TAG PARA MALA": { linhaRetaM: 100, etiqueta: 1 },
  "COOLER TÉRMICO GRANDE": { linhaZigM: 2500, linhaRetaM: 3000, ziper80CM: 1, fitaRigida: { largura: null, cmPeca: 520 }, poliester: { largura: null, cmPeca: 190 }, mosquetao: { NIQUELADO: 2 }, passador: { NIQUELADO: 1 }, meiaArgola: { NIQUELADO: 2 }, etiqueta: 1 },
  "COOLER TÉRMICO PEQUENO": { linhaZigM: 2000, linhaRetaM: 3000, ziper80CM: 1, fitaRigida: { largura: null, cmPeca: 400 }, poliester: { largura: null, cmPeca: 190 }, mosquetao: { NIQUELADO: 2 }, passador: { NIQUELADO: 1 }, meiaArgola: { NIQUELADO: 2 }, etiqueta: 1 },
  "TAPA OLHO": { linhaRetaM: 150, fitaRigida: { largura: 2.05, cmPeca: 60 }, elastico: { largura: 2.03, cmPeca: 38 } },
  "VISEIRA": { linhaZigM: 100, linhaRetaM: 500, fitaRigida: { largura: 2.05, cmPeca: 120 }, etiqueta: 1, velcro: 8 },
  "LATA CAMISA": { linhaZigM: 300 },
  "LONG CAMISA": { linhaZigM: 300 },
  "CANGA DE PRAIA": { linhaRetaM: 500, pompom: { largura: null, cmPeca: 110 }, etiqueta: 1 },
  "CANGA DE PRAIA G": {},
  "MARMITEIRA IMPERMEÁVEL": { elasticoRaboDeGato: { largura: null, cmPeca: 170 }, poliester: { largura: null, cmPeca: 140 }, meiaArgola: { NIQUELADO: 3 }, reguladorFocinhoPorco: 2, forroTermico: 1 },
  "MOCHILA IMPERMEÁVEL": { ziper30CM: 1, cordasPoliester: { largura: null, cmPeca: 330 }, forroImpermeavel: 1 },
  "VISEIRA TURBANTE": { fitaRigida: { largura: null, cmPeca: 55 }, elasticoFF: { largura: 10, cmPeca: 15 }, etiqueta: 1 },
  "ESTEIRA DE PRAIA": { ziper50CM: 1, fitaRigida: { largura: null, cmPeca: 800 }, etiqueta: 1 },
  "WINE CASE DELUXE": { linhaRetaM: 500, ziper80CM: 1, fitaRigida: { largura: null, cmPeca: 500 }, poliester: { largura: null, cmPeca: 220 }, mosquetao: { NIQUELADO: 2 }, passador: { NIQUELADO: 1 }, meiaArgola: { NIQUELADO: 2 }, etiqueta: 1, forroImpermeavel: 1, plasticoDuro: 1, telaBolso: 1, forroMatelace: 1 },
  "WINE BAG": { linhaZigM: 100, linhaRetaM: 500, ziper35CM: 1, fitaRigida: { largura: null, cmPeca: 550 }, poliester: { largura: null, cmPeca: 180 }, mosquetao: { NIQUELADO: 2 }, fecho: { NIQUELADO: 1 }, meiaArgola: { NIQUELADO: 2 }, etiqueta: 1, forroImpermeavel: 1, plasticoDuro: 1, forroMatelace: 2 }
};

export const EXCLUDED_SEWING_PRODUCTS = ["MÁSCARA PROTETORA", "MOUSE PAD", "MOUSE PAD GAMER", "PORTA COPOS"];
