const SG_EXCLUDED=new Set(['MÁSCARA PROTETORA','MOUSE PAD','MOUSE PAD GAMER','PORTA COPOS']);
const sgRead=()=>{try{const x=JSON.parse(localStorage.getItem('almox-lists')||'[]');return Array.isArray(x)?x:[]}catch{return[]}};
const sgEsc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sgFmt=n=>Number.isInteger(Number(n))?String(Number(n)):Number(n||0).toFixed(2).replace(/\.00$/,'');
function sgRender(){const o=document.getElementById('costura-dispatch-overlay');if(!o)return;const lists=sgRead();const grouped=new Map();let total=0;lists.forEach(l=>{Object.values(l?.items||{}).forEach(x=>{if(!x?.product||SG_EXCLUDED.has(String(x.product).trim().toUpperCase()))return;const qty=Number(x.total)||0;if(qty<=0)return;const color=x.color||'SEM COR';const key=`${x.product}__${color}`;if(!grouped.has(key))grouped.set(key,{product:x.product,color,qty:0,lists:[]});const g=grouped.get(key);g.qty+=qty;g.lists.push({name:l.name||'Lista',qty});total+=qty;});});
const byProduct=new Map();[...grouped.values()].forEach(g=>{if(!byProduct.has(g.product))byProduct.set(g.product,{product:g.product,total:0,colors:[]});const p=byProduct.get(g.product);p.total+=g.qty;p.colors.push(g)});
const body=o.querySelector('.cd-body');if(!byProduct.size){body.innerHTML='<div class="cd-empty">Nenhum saldo disponível para costura nas listas.</div>';return}
body.innerHTML='<div class="cd-summary"><b>SALDO GERAL DA SEPARAÇÃO</b><br><span>Mostrando o que ainda permanece nas listas e, portanto, ainda não foi enviado para a costura.</span><br><b>Total disponível:</b> '+sgFmt(total)+' peças · <b>Produtos:</b> '+byProduct.size+'</div><div class="cd-toolbar"><button class="cd-btn cd-muted" id="sg-refresh">↻ ATUALIZAR</button></div>'+[...byProduct.values()].sort((a,b)=>a.product.localeCompare(b.product,'pt-BR')).map(p=>'<div class="cd-batch"><div class="cd-batch-head"><div><b>'+sgEsc(p.product)+'</b><br><span class="cd-badge">TOTAL: '+sgFmt(p.total)+' UN</span></div></div><div class="cd-batch-body">'+p.colors.sort((a,b)=>a.color.localeCompare(b.color,'pt-BR')).map(c=>'<div class="cd-item"><span><b>'+sgEsc(c.color)+'</b><br><small>'+c.lists.map(l=>sgEsc(l.name)+': '+sgFmt(l.qty)).join(' · ')+'</small></span><b>'+sgFmt(c.qty)+'</b></div>').join('')+'</div></div>').join('');o.querySelector('#sg-refresh').onclick=sgRender}
function sgMount(){const overlay=document.getElementById('costura-dispatch-overlay');if(!overlay||overlay.dataset.sgReady)return;overlay.dataset.sgReady='1';const tabs=overlay.querySelector('.cd-tabs');if(!tabs)return;const b=document.createElement('button');b.className='cd-tab';b.dataset.tab='saldo';b.textContent='📦 Saldo geral';b.onclick=sgRender;tabs.appendChild(b)}
const sgObserver=new MutationObserver(()=>sgMount());sgObserver.observe(document.body,{childList:true,subtree:true});setInterval(sgMount,700);
